### ISSUE TITLE
Auth: Fee Updates for new incorporation types

### ISSUE THREAD

**Issue by cameron-freshworks** [bcgov/sbc-auth#1654]
- With the introduction of Limited companies, Unlimited Companies and Community Contribution Companies, we will need incorporation fee codes for these types as well as identify the fee amounts for Relationships team to assign.

**Comment by seeker25** [comment]
Should this be in PAY instead of AUTH?

**Comment by cameron-freshworks** [comment]
> Should this be in PAY instead of AUTH?

I'm not too sure what work there would be in the API's, this is before i knew about the self-serve pay admin tool:
https://pay-admin-dev.apps.silver.devops.gov.bc.ca/admin/filingtype/

Once the code/fee schedule is created there, is there still work to do in Pay/Auth api's?

**Comment by seeker25** [comment]
Moving this to pay.
