### ISSUE TITLE
Can't run in Dev mode.  Got HTTP Request Loop

### ISSUE THREAD

**Issue by rolia-net** [bcgov/sbc-auth#2354]
**Describe the bug**
The auth-web would create a HTTP request loop when accessing the web page of http://localhost:8080/ 

**To Reproduce**
1. Follow the instructions to set up the environment
2. Run the environment in local dev 
3. Access http://localhost:8080/ in a browser
4. Got HTTP 431 error after a while
6. The URL would become:

http://localhost:8080/undefined/realms/undefined/protocol/openid-connect/undefined/realms/undefined/protocol/openid-connect/undefined/realms/undefined/protocol/openid-connect/undefined/realms/undefined/protocol/openid-connect/undefined/realms/undefined/protocol/openid-connect/undefined/realms/undefined/protocol/openid-connect/undefined/realms/undefined/protocol/openid-connect/undefined/realms/undefined/protocol/openid-connect/undefined/realms/undefined/protocol/openid-connect/undefined/realms/undefined/protocol/openid-connect/undefined/realms/undefined/protocol/openid-connect/undefined/realms/undefined/protocol/openid-connect/undefined/realms/undefined/protocol/openid-connect/auth?client_id=undefined&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fundefined%2Frealms%2Fundefined%2Fprotocol%2Fopenid-connect%2Fundefined%2Frealms%2Fundefined%2Fprotocol%2Fopenid-connect%2Fundefined%2Frealms%2Fundefined%2Fprotocol%2Fopenid-connect%2Fundefined%2Frealms%2Fundefined%2Fprotocol%2Fopenid-connect%2Fundefined%2Frealms%2Fundefined%2Fprotocol%2Fopenid-connect%2Fundefined%2Frealms%2Fundefined%2Fprotocol%2Fopenid-connect%2Fundefined%2Frealms%2Fundefined%2Fprotocol%2Fopenid-connect%2Fundefined%2Frealms%2Fundefined%2Fprotocol%2Fopenid-connect%2Fundefined%2Frealms%2Fundefined%2Fprotocol%2Fopenid-connect%2Fundefined%2Frealms%2Fundefined%2Fprotocol%2Fopenid-connect%2Fundefined%2Frealms%2Fundefined%2Fprotocol%2Fopenid-connect%2Fundefined%2Frealms%2Fundefined%2Fprotocol%2Fopenid-connect%2Fauth%3Fclient_id%3Dundefined%26redirect_uri%3Dhttp%253A%252F%252Flocalhost%253A8080%252Fundefined%252Frealms%252Fundefined%252Fprotocol%252Fopenid-connect%252Fundefined%252Frealms%252Fundefined%252Fprotocol%252Fopenid-connect%252Fundefined%252Frealms%252Fundefined%252Fprotocol%252Fopenid-connect%252Fundefined%252Frealms%252Fundefined%252Fprotocol%252Fopenid-connect%252Fundefined%252Frealms%252Fundefined%252Fprotocol%252Fopenid-connect%252Fundefined%252Frealms%252Fundefined%252Fprotocol%252Fopenid-connect%252Fundefined%252Frealms%252Fundefined%252Fprotocol%252Fopenid-connect%252Fundefined%252Frealms%252Fundefined%252Fprotocol%252Fopenid-connect%252Fundefined%252Frealms%252Fundefined%252Fprotocol%252Fopenid-connect%252Fundefined%252Frealms%252Fundefined%252Fprotocol%252Fopenid-connect%252Fundefined%252Frealms%252Fundefined%252Fprotocol%252Fopenid-connect%252Fauth%253Fclient_id%253Dundefined%2526redirect_uri%253Dhttp%25253A%25252F%25252Flocalhost%25253A8080%25252Fundefined%25252Frealms%25252Fundefined%25252Fprotocol%25252Fopenid-connect%25252Fundefined%25252Frealms%25252Fundefined%25252Fprotocol%25252Fopenid-connect%25252Fundefined%25252Frealms%25252Fundefined%25252Fprotocol%25252Fopenid-connect%25252Fundefined%25252Frealms%25252Fundefined%25252Fprotocol%25252Fopenid-connect%25252Fundefined%25252Frealms%25252Fundefined%25252Fprotocol%25252Fopenid-connect%25252Fundefined%25252Frealms%25252Fundefined%25252Fprotocol%25252Fopenid-connect%25252Fundefined%25252Frealms%25252Fundefined%25252Fprotocol%25252Fopenid-connect%25252Fundefined%25252Frealms%25252Fundefined%25252Fprotocol%25252Fopenid-connect%25252Fundefined%25252Frealms%25252Fundefined%25252Fprotocol%25252Fopenid-connect%25252Fundefined%25252Frealms%25252Fundefined%25252Fprotocol%25252Fopenid-connect%25252Fauth%25253Fclient_id%25253Dundefined%252526redirect_uri%25253Dhttp%2525253A%2525252F%2525252Flocalhost%2525253A8080%2525252Fundefined%2525252Frealms%2525252Fundefined%2525252Fprotocol%2525252Fopenid-connect%2525252Fundefined%2525252Frealms%2525252Fundefined%2525252Fprotocol%2525252Fopenid-connect%2525252Fundefined%2525252Frealms%2525252Fundefined%2525252Fprotocol%2525252Fopenid-connect%2525252Fundefined%2525252Frealms%2525252Fundefined%2525252Fprotocol%2525252Fopenid-connect%2525252Fundefined%2525252Frealms%2525252Fundefined%2525252Fprotocol%2525252Fopenid-connect%2525252Fundefined%2525252Frealms%2525252Fundefined%2525252Fprotocol%2525252Fopenid-connect%2525252Fundefined%2525252Frealms%2525252Fundefined%2525252Fprotocol%2525252Fopenid-connect%2525252Fundefined%2525252Frealms%2525252Fundefined%2525252Fprotocol%2525252Fopenid-connect%2525252Fundefined%2525252Frealms%2525252Fundefined%2525252Fprotocol%2525252Fopenid-connect%2525252Fauth%2525253Fclient_id%2525253Dundefined%25252526redirect_uri%2525253Dhttp%252525253A%252525252F%252525252Flocalhost%252525253A8080%252525252Fundefined%252525252Frealms%252525252Fundefined%252525252Fprotocol%252525252Fopenid-connect%252525252Fundefined%252525252Frealms%252525252Fundefined%252525252Fprotocol%252525252Fopenid-connect%252525252Fundefined%252525252Frealms%252525252Fundefined%252525252Fprotocol%252525252Fopenid-connect%252525252Fundefined%252525252Frealms%252525252Fundefined%252525252Fprotocol%252525252Fopenid-connect%252525252Fundefined%252525252Frealms%252525252Fundefined%252525252Fprotocol%252525252Fopenid-connect%252525252Fundefined%252525252Frealms%252525252Fundefined%252525252Fprotocol%252525252Fopenid-connect%252525252Fundefined%252525252Frealms%252525252Fundefined%252525252Fprotocol%252525252Fopenid-connect%252525252Fundefined%252525252Frealms%252525252Fundefined%252525252Fprotocol%252525252Fopenid-connect%252525252Fauth%252525253Fclient_id%252525253Dundefined%2525252526redirect_uri%252525253Dhttp%25252525253A%25252525252F%25252525252Flocalhost%25252525253A8080%25252525252Fundefined%25252525252Frealms%25252525252Fundefined%25252525252Fprotocol%25252525252Fopenid-connect%25252525252Fundefined%25252525252Frealms%25252525252Fundefined%25252525252Fprotocol%25252525252Fopenid-connect%25252525252Fundefined%25252525252Frealms%25252525252Fundefined%25252525252Fprotocol%25252525252Fopenid-connect%25252525252Fundefined%25252525252Frealms%25252525252Fundefined%25252525252Fprotocol%25252525252Fopenid-connect%25252525252Fundefined%25252525252Frealms%25252525252Fundefined%25252525252Fprotocol%25252525252Fopenid-connect%25252525252Fundefined%25252525252Frealms%25252525252Fundefined%25252525252Fprotocol%25252525252Fopenid-connect%25252525252Fundefined%25252525252Frealms%25252525252Fundefined%25252525252Fprotocol%25252525252Fopenid-connect%25252525252Fauth%25252525253Fclient_id%25252525253Dundefined%252525252526redirect_uri%25252525253Dhttp%2525252525253A%2525252525252F%2525252525252Flocalhost%2525252525253A8080%2525252525252Fundefined%2525252525252Frealms%2525252525252Fundefined%2525252525252Fprotocol%2525252525252Fopenid-connect%2525252525252Fundefined%2525252525252Frealms%2525252525252Fundefined%2525252525252Fprotocol%2525252525252Fopenid-connect%2525252525252Fundefined%2525252525252Frealms%2525252525252Fundefined%2525252525252Fprotocol%2525252525252Fopenid-connect%2525252525252Fundefined%2525252525252Frealms%2525252525252Fundefined%2525252525252Fprotocol%2525252525252Fopenid-connect%2525252525252Fundefined%2525252525252Frealms%2525252525252Fundefined%2525252525252Fprotocol%2525252525252Fopenid-connect%2525252525252Fundefined%2525252525252Frealms%2525252525252Fundefined%2525252525252Fprotocol%2525252525252Fopenid-connect%2525252525252Fauth%2525252525253Fclient_id%2525252525253Dundefined%25252525252526redirect_uri%2525252525253Dhttp%252525252525253A%252525252525252F%252525252525252Flocalhost%252525252525253A8080%252525252525252Fundefined%252525252525252Frealms%252525252525252Fundefined%252525252525252Fprotocol%252525252525252Fopenid-connect%252525252525252Fundefined%252525252525252Frealms%252525252525252Fundefined%252525252525252Fprotocol%252525252525252Fopenid-connect%252525252525252Fundefined%252525252525252Frealms%252525252525252Fundefined%252525252525252Fprotocol%252525252525252Fopenid-connect%252525252525252Fundefined%252525252525252Frealms%252525252525252Fundefined%252525252525252Fprotocol%252525252525252Fopenid-connect%252525252525252Fundefined%252525252525252Frealms%252525252525252Fundefined%252525252525252Fprotocol%252525252525252Fopenid-connect%252525252525252Fauth%252525252525253Fclient_id%252525252525253Dundefined%2525252525252526redirect_uri%252525252525253Dhttp%25252525252525253A%25252525252525252F%25252525252525252Flocalhost%25252525252525253A8080%25252525252525252Fundefined%25252525252525252Frealms%25252525252525252Fundefined%25252525252525252Fprotocol%25252525252525252Fopenid-connect%25252525252525252Fundefined%25252525252525252Frealms%25252525252525252Fundefined%25252525252525252Fprotocol%25252525252525252Fopenid-connect%25252525252525252Fundefined%25252525252525252Frealms%25252525252525252Fundefined%25252525252525252Fprotocol%25252525252525252Fopenid-connect%25252525252525252Fundefined%25252525252525252Frealms%25252525252525252Fundefined%25252525252525252Fprotocol%25252525252525252Fopenid-connect%25252525252525252Fauth%25252525252525253Fclient_id%25252525252525253Dundefined%252525252525252526redirect_uri%25252525252525253Dhttp%2525252525252525253A%2525252525252525252F%2525252525252525252Flocalhost%2525252525252525253A8080%2525252525252525252Fundefined%2525252525252525252Frealms%2525252525252525252Fundefined%2525252525252525252Fprotocol%2525252525252525252Fopenid-connect%2525252525252525252Fundefined%2525252525252525252Frealms%2525252525252525252Fundefined%2525252525252525252Fprotocol%2525252525252525252Fopenid-connect%2525252525252525252Fundefined%2525252525252525252Frealms%2525252525252525252Fundefined%2525252525252525252Fprotocol%2525252525252525252Fopenid-connect%2525252525252525252Fauth%2525252525252525253Fclient_id%2525252525252525253Dundefined%25252525252525252526redirect_uri%2525252525252525253Dhttp%252525252525252525253A%252525252525252525252F%252525252525252525252Flocalhost%252525252525252525253A8080%252525252525252525252Fundefined%252525252525252525252Frealms%252525252525252525252Fundefined%252525252525252525252Fprotocol%252525252525252525252Fopenid-connect%252525252525252525252Fundefined%252525252525252525252Frealms%252525252525252525252Fundefined%252525252525252525252Fprotocol%252525252525252525252Fopenid-connect%252525252525252525252Fauth%252525252525252525253Fclient_id%252525252525252525253Dundefined%2525252525252525252526redirect_uri%252525252525252525253Dhttp%25252525252525252525253A%25252525252525252525252F%25252525252525252525252Flocalhost%25252525252525252525253A8080%25252525252525252525252Fundefined%25252525252525252525252Frealms%25252525252525252525252Fundefined%25252525252525252525252Fprotocol%25252525252525252525252Fopenid-connect%25252525252525252525252Fauth%25252525252525252525253Fclient_id%25252525252525252525253Dundefined%252525252525252525252526redirect_uri%25252525252525252525253Dhttp%2525252525252525252525253A%2525252525252525252525252F%2525252525252525252525252Flocalhost%2525252525252525252525253A8080%2525252525252525252525252F%252525252525252525252526state%25252525252525252525253D68388959-7238-45f7-8ad1-9ffa4300fd0c%252525252525252525252526response_mode%25252525252525252525253Dfragment%252525252525252525252526response_type%25252525252525252525253Dcode%252525252525252525252526scope%25252525252525252525253Dopenid%252525252525252525252526nonce%25252525252525252525253D56a38af1-3d4a-42f5-a434-632df49cd7be%252525252525252525252526prompt%25252525252525252525253Dnone%252525252525252525252526code_challenge%25252525252525252525253DgxL3HBYtzpG7magUlhdRyp-zF7drt7CifcyT1mmryeU%252525252525252525252526code_challenge_method%25252525252525252525253DS256%2525252525252525252526state%252525252525252525253Df6683ec3-e689-43a2-bb61-ce945974c1a0%2525252525252525252526response_mode%252525252525252525253Dfragment%2525252525252525252526response_type%252525252525252525253Dcode%2525252525252525252526scope%252525252525252525253Dopenid%2525252525252525252526nonce%252525252525252525253D3e82e0b0-3736-426e-9800-f44276296545%2525252525252525252526prompt%252525252525252525253Dnone%2525252525252525252526code_challenge%252525252525252525253Da5VJhEA0qashp8FXpIPB-O6sPFr2gOp9e0VHjr8CyMM%2525252525252525252526code_challenge_method%252525252525252525253DS256%25252525252525252526state%2525252525252525253D64e4d736-1b75-45cf-95e8-2800330e8acf%25252525252525252526response_mode%2525252525252525253Dfragment%25252525252525252526response_type%2525252525252525253Dcode%25252525252525252526scope%2525252525252525253Dopenid%25252525252525252526nonce%2525252525252525253Df9431be2-bf3e-4553-8bed-dda02fec5db5%25252525252525252526prompt%2525252525252525253Dnone%25252525252525252526code_challenge%2525252525252525253DyvK_dnJ-U7hXSHsyLwekm30p3M3qA5_B0dben9JY-PI%25252525252525252526code_challenge_method%2525252525252525253DS256%252525252525252526state%25252525252525253D43265f26-391a-4aa4-85b3-263d19e68a09%252525252525252526response_mode%25252525252525253Dfragment%252525252525252526response_type%25252525252525253Dcode%252525252525252526scope%25252525252525253Dopenid%252525252525252526nonce%25252525252525253D21a8c78c-69bb-45f0-9b47-4aa4abd274ae%252525252525252526prompt%25252525252525253Dnone%252525252525252526code_challenge%25252525252525253DmxqeaGF_yjCPZjWBSEjX9j_GwbDRXx18NNXO54kTGP4%252525252525252526code_challenge_method%25252525252525253DS256%2525252525252526state%252525252525253D3882a31d-370e-4218-b618-11e17a6def2e%2525252525252526response_mode%252525252525253Dfragment%2525252525252526response_type%252525252525253Dcode%2525252525252526scope%252525252525253Dopenid%2525252525252526nonce%252525252525253D0935156f-2c4f-429a-9ddc-17c36f3e3fe8%2525252525252526prompt%252525252525253Dnone%2525252525252526code_challenge%252525252525253DKZnuJdkXOlhs7yHA3NpzM1pPBhtXZ2oMbXCiimKMXr0%2525252525252526code_challenge_method%252525252525253DS256%25252525252526state%2525252525253D9c9d2a08-0dc4-4c2a-a1f5-46848c08a9ca%25252525252526response_mode%2525252525253Dfragment%25252525252526response_type%2525252525253Dcode%25252525252526scope%2525252525253Dopenid%25252525252526nonce%2525252525253D3d6efe2d-dfbc-42a2-8c41-7859e0a6778f%25252525252526prompt%2525252525253Dnone%25252525252526code_challenge%2525252525253DvW1Tf0FFdq_jFAwbVRNpX0XSuPaQGr7kIJMmt6xcz40%25252525252526code_challenge_method%2525252525253DS256%252525252526state%25252525253Db95781c1-2555-4dfe-a422-37133828649a%252525252526response_mode%25252525253Dfragment%252525252526response_type%25252525253Dcode%252525252526scope%25252525253Dopenid%252525252526nonce%25252525253D5dd2dd39-e9b7-4167-bc1d-4f7ba00d6f6d%252525252526prompt%25252525253Dnone%252525252526code_challenge%25252525253DqCylP1AayClXLyf0ea8YiIeU1xk1o6KBSCabCVcu-us%252525252526code_challenge_method%25252525253DS256%2525252526state%252525253D9d0a84ba-3a83-46a6-a59f-353e895f6736%2525252526response_mode%252525253Dfragment%2525252526response_type%252525253Dcode%2525252526scope%252525253Dopenid%2525252526nonce%252525253D0052edae-dccb-43be-b065-d43c1a03464f%2525252526prompt%252525253Dnone%2525252526code_challenge%252525253DMCKSBa-ia6Oq875zlg3JT6Z9AshTGNmExB3I3F2xzR4%2525252526code_challenge_method%252525253DS256%25252526state%2525253D9d929d14-1906-42fb-9382-a3e272a4726d%25252526response_mode%2525253Dfragment%25252526response_type%2525253Dcode%25252526scope%2525253Dopenid%25252526nonce%2525253D1888005f-33a4-4856-94b3-94bc70ef1f43%25252526prompt%2525253Dnone%25252526code_challenge%2525253D7Bq4OqiUdqucjsvhDTv-qHVMGBIoBzujAO1LzAHpk4U%25252526code_challenge_method%2525253DS256%252526state%25253D240f10fc-6748-46a7-98f8-43ac2f2733a8%252526response_mode%25253Dfragment%252526response_type%25253Dcode%252526scope%25253Dopenid%252526nonce%25253Da7148eb5-a22a-4917-8375-54192e1cc577%252526prompt%25253Dnone%252526code_challenge%25253DEhbHuABtJ32jx0gpJOYSin_jtmn_xshxP2oKazP_srE%252526code_challenge_method%25253DS256%2526state%253Da604b764-5cab-4d8f-83b6-a292cf271778%2526response_mode%253Dfragment%2526response_type%253Dcode%2526scope%253Dopenid%2526nonce%253D33c77431-7221-4f2e-97a3-7a8f1ce1bbaf%2526prompt%253Dnone%2526code_challenge%253DC8BY0a8oku2Pz50RFdwR6K_5CiL0hRjynLvsbMebOaQ%2526code_challenge_method%253DS256%26state%3Ddb1efb41-105c-497e-8581-605cbfd342f8%26response_mode%3Dfragment%26response_type%3Dcode%26scope%3Dopenid%26nonce%3Ded554cb1-3dab-4d40-9691-c02dd43e1afc%26prompt%3Dnone%26code_challenge%3DcmMXzKdKt-aGymiWUz4EWL8znnPXOWnIidMrKNzTRD4%26code_challenge_method%3DS256&state=e61996b1-b359-4537-8be0-892cab7f5b18&response_mode=fragment&response_type=code&scope=openid&nonce=77707773-da01-488a-a799-1b75e89bba0d&prompt=none&code_challenge=FoW9U4OE6pxJWxK4Y5MrTdaYwNUfK0qLEvAZeTu6vPU&code_challenge_method=S256

**Comment by seeker25** [comment]
Need the secrets, otherwise you'll run into this - it should point to the keycloak instance
