### ISSUE TITLE
Director search

### ISSUE THREAD

**Issue by bcdevex** [bcgov/sbc-auth#288]
<p>This issue has been auto-generated to facilitate questions about
<a href="https://bcdevexchange.org/opportunities/cwu/opp-director-search"> a paid opportunity</a> that has just been posted on the
<a href="https://bcdevexchange.org">BCDevExchange</a>.</p>

<p>To learn more or apply, <a href="https://bcdevexchange.org/opportunities/cwu/opp-director-search">visit the opportunity page</a>.
The opportunity closes on <b>Thursday, December 12th, 2019 at 16:00 PST</b>.</p>

**Comment by lmullane** [comment]
Hi all, 

I'm the product owner for this opportunity. If you have any questions, please post them here and I will respond as soon as I can.

**Comment by lxcor** [comment]
Hi Loren, Have you assigned this opportunity?

**Comment by lmullane** [comment]
Apologies, I have not yet. I will post once the opportunity is assigned.

**Comment by lmullane** [comment]
Hi all,

Thank you to those who submitted a proposal. We received some excellent proposals.
 
We have concluded our evaluation and of the four proposals received. The opportunity has been assigned to the Countable, the highest scoring proponent.

If you would like feedback on your proposal, please contact me by email at Loren.Mullane@gov.bc.ca to set up a time.

**Comment by bcdevex** [comment]
This opportunity has been assigned

**Comment by trishreimer** [comment]
Hi Loren, Would you mind letting me know when the canvas has been developed?
